server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    url: jdbc:mysql://149.28.50.23:3306/tensquare_base?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 149.28.50.234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    #可以跨域
    prefer-ip-address: true
