server:
  port: 9011
spring:
  application:
    name: tensquare-manager
  rabbitmq:
    host: 149.28.50.234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
    instance:
      prefer-ip-address: true
jwt:
  config:
    key: superbrain
    ttl: 3600000
zuul:
  routes:
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-search:
      path: /search/**
      serviceId: tensquare-search
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
