server:
  port: 9007
spring:
  application:
    name: tensquare-search
  rabbitmq:
    host: 149.28.50.234
  data:
  elasticsearch:
    rest:
      uris: ["http://149.28.50.234:9200"]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
