server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  rabbitmq:
    host: 149.28.50.234
  data:
    mongodb:
      host: 149.28.50.234
      database: spitdb
  redis:
    host: 149.28.50.234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
